name = "boni-learns-fortran"
version = "0.1.0"
license = "MIT"
author = "Boni Lindsley"
maintainer = "boni@lindsley.xyz"
copyright = "Copyright 2022, Boni Lindsley"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
